### ISSUE TITLE
Can't use updated files from IANA

### ISSUE THREAD

**Issue by bfis108137** [LZorglub/TimeZone#4]
When I download the files manually, I get an exception.  "The type initializer for 'Afk.ZoneInfo.TzTimeInfo' threw an exception."

I looked at it a little in the debugger and it seems there is some duplicate key error.  BTW, it seems that it happens even with the current files.  I copied the current files in the data folder to another folder and defined that folder in the env var TZDIR and the same thing happens.

Just to be clear,  I just download https://www.iana.org/time-zones/repository/tzdata-latest.tar.gz and unpack it into a directory.  That is my TZDIR.

**Comment by LZorglub** [comment]
Some files must be delete from your TZDIR archive (backzone, calendars, makefile, news, readme and version) 

In next version we will ignore this files.

**Comment by LZorglub** [comment]
Closed due to inactivity
